name: CI1

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
        
      - name: Build with Ant
        run: ant -f build-auto.xml dist
        
      - name: Move builds to appropriate artifact folders
        run: |
          # Remove all unnecessary build folders since we will only release builds archived with 7-Zip
          cd dist
          rm -R -- */
          cd ..
          # Make directories for artifact releases and move each build to their respective folders
          mkdir -p dist/{buildWindows/x86,buildWindows/amd64,buildLinux/x86,buildLinux/amd64,buildmacOS}
          mv dist/*linux-amd64* dist/buildLinux/amd64/
          mv dist/*linux-x86* dist/buildLinux/x86/
          mv dist/*windows-x86* dist/buildWindows/x86/
          mv dist/*windows-amd64* dist/buildWindows/amd64/
          mv dist/*macosx* dist/buildmacOS/
     
      - name: Publishing Windows 32-bit build
        uses: actions/upload-artifact@v2
        with:
          name: Windows 32-bit build
          path: dist/buildWindows/x86

      - name: Publishing Windows 64-bit build
        uses: actions/upload-artifact@v2
        with:
          name: Windows 64-bit build
          path: dist/buildWindows/amd64
      
      - name: Publishing Linux 32-bit build
        uses: actions/upload-artifact@v2
        with:
          name: Linux 32-bit build
          path: dist/buildLinux/x86

      - name: Publishing Linux 64-bit build
        uses: actions/upload-artifact@v2
        with:
          name: Linux 64-bit build
          path: dist/buildLinux/amd64

      - name: Publishing macOS build
        uses: actions/upload-artifact@v2
        with:
          name: macOS build
          path: dist/buildmacOS
          
      - name: Release tagged builds
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/buildLinux/x86/*.7z
            dist/buildLinux/amd64/*.7z
            dist/buildmacOS/*.7z
            dist/buildWindows/x86/*.7z
            dist/buildWindows/amd64/*.7z
